version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST: db
      POSTGRES_DB: avby-docker
    ports:
      - "5433:5432"

  backend:
    image: my-django-app
    container_name: my-django
    ports:
      - "8000:8000"
    depends_on:
      - postgres