# Generated by Django 5.0.3 on 2024-04-12 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_tguser_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Пользователь телеграм', 'verbose_name_plural': 'Пользователи телеграм'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.tguser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Телеграм ID'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
    ]
