# Generated by Django 5.0.3 on 2024-04-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_chat_options_alter_tguser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tg_id',
            field=models.PositiveIntegerField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name='Телеграм ID'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя'),
        ),
    ]
