# Generated by Django 5.0.3 on 2024-04-08 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Марка')),
                ('image', models.ImageField(upload_to='cars_brands/', verbose_name='Изображение марки')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слуг марки')),
            ],
        ),
        migrations.RemoveField(
            model_name='carphoto',
            name='photo_url',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_body',
            field=models.CharField(blank=True, max_length=20, verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(blank=True, max_length=20, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Тип привода'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.CharField(blank=True, max_length=20, verbose_name='Объем двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='car',
            name='milage',
            field=models.CharField(blank=True, max_length=20, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Слуг автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Тип трансмиссии'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(blank=True, max_length=10, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='carphoto',
            name='photo',
            field=models.ImageField(upload_to='cars_photo/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.carbrand'),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слуг модели')),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.carbrand')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.carmodel'),
        ),
    ]
