# Generated by Django 5.0.3 on 2024-04-08 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carbrand_remove_carphoto_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.carbrand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars_brands/', verbose_name='Изображение марки'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.carbrand', verbose_name='Марка'),
        ),
    ]
