# Generated by Django 5.0.3 on 2024-04-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_brand_alter_car_model_alter_carbrand_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Модель'),
        ),
    ]
