# Generated by Django 5.0.3 on 2024-04-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_options_alter_carbrand_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка на объявление')),
            ],
        ),
    ]
