# Generated by Django 5.0.3 on 2024-04-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_views_count_alter_carphoto_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
