# Generated by Django 5.0.3 on 2024-03-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofileinfo_created_userprofileinfo_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
