# Generated by Django 5.0.3 on 2024-03-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofileinfo_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='telegram_attached',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
