# Generated by Django 5.0.3 on 2024-04-02 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_tguser_created'),
        ('user', '0005_userprofileinfo_telegram_attached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='image',
            field=models.ImageField(blank=True, default='user-noimage.webp', null=True, upload_to='user_photos'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='telegram',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tg_profile', to='telegram.tguser'),
        ),
    ]
