# Generated by Django 5.0.3 on 2024-04-12 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_chat_options_alter_tguser_options_and_more'),
        ('user', '0006_userprofileinfo_image_alter_userprofileinfo_telegram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofileinfo',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='image',
            field=models.ImageField(blank=True, default='user_photos/user-noimage.webp', null=True, upload_to='user_photos/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='telegram',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tg_profile', to='telegram.tguser', verbose_name='Телеграм идентификатор'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='telegram_attached',
            field=models.BooleanField(default=False, verbose_name='Привязан телеграм'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
