# Generated by Django 5.0.3 on 2024-04-23 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_views_count'),
        ('user', '0008_favoritescars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritescars',
            options={'verbose_name': 'Изранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='telegram_attached',
        ),
        migrations.AlterField(
            model_name='favoritescars',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='cars.car', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='favoritescars',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_cars', to='user.userprofileinfo', verbose_name='Пользователь'),
        ),
    ]
