# Generated by Django 5.0.3 on 2024-04-26 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_alter_tguser_tg_id_alter_tguser_username'),
        ('user', '0009_alter_favoritescars_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='telegram',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_profile', to='telegram.tguser', verbose_name='Телеграм профиль'),
        ),
    ]
